### PR TITLE
Updating to the newer persistent

### PR DESCRIPTION
**Pull request by maksar**

### CODE REVIEW

**Review by MichaelXavier — COMMENTED** [review]
Does this require lower bounds to be set on persistent?

**Review by MichaelXavier — APPROVED** [review]

**Comment by MichaelXavier** [comment]
@maksar Looks good! Should I merge and then bump the version from 0.6.1 to 0.7.0 (due to the type change) and then release?

**Comment by maksar** [comment]
@MichaelXavier Would be great. Many thanks

**Comment by MichaelXavier** [comment]
@maksar it ended up being 0.7.1

**Pull request merged**
